language: zh
pipeline:
- name: "JiebaTokenizer"  #分词器
  dictionary_path: "data/dict"
- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "bert-base-chinese"

- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4

- name: DIETClassifier
  epochs: 30
  learning_rate: 0.005
  number_of_transformer_layers: 0
  embedding_dimension: 30
  #hidden_layers_sizes:
    #text: [256, 128]

- name: "EntitySynonymMapper"  #同义词
- name: "RegexFeaturizer"     #正则

policies:
  - name: AugmentedMemoizationPolicy

  - name: TEDPolicy
    epochs: 100
    featurizer:
    - name: MaxHistoryTrackerFeaturizer
      max_history: 5
      state_featurizer:
        - name: BinarySingleStateFeaturizer


  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
    nlu_threshold: 0.5
    core_threshold: 0.3
    ambiguity_threshold: 0.1

  - name: MappingPolicy





#language: "zh"
#
#pipeline:
#- name: "JiebaTokenizer"
#- name: "CRFEntityExtractor"
#
#- name: "rasa_nlu_gao.extractors.jieba_pseg_extractor.JiebaPsegExtractor"
#  part_of_speech: ["nr"]
#
#- name: "rasa_nlu_gao.featurizers.bert_vectors_featurizer.BertVectorsFeaturizer"
#  ip: '127.0.0.1'
#  port: 5555
#  port_out: 5556
#  show_server_config: True
#  timeout: 10000
#  check_version: False
#- name: "rasa_nlu_gao.classifiers.embedding_bert_intent_classifier.EmbeddingBertIntentClassifier"
#
#policies:
#  - name: "policy.attention_policy.AttentionPolicy"
#    epochs: 100
#    featurizer:
#    - name: MaxHistoryTrackerFeaturizer
#      max_history: 3
#      state_featurizer:
#        - name: LabelTokenizerSingleStateFeaturizer
#    tf_config: {
#      "inter_op_parallelism_threads": 0,
#      "intra_op_parallelism_threads": 0,
#      "gpu_options": {"allow_growth": True}
#    }
#
#  - name: FallbackPolicy
#    fallback_action_name: 'action_default_fallback'
#    nlu_threshold: 0.5
#    core_threshold: 0.3
#  - name: MemoizationPolicy
#    max_history: 3